EnvironmentConfigurationMetadata:
  DateCreated: '1533920525000'
  DateModified: '1533920525000'
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on 64bit Amazon Linux/4.5.1
OptionSettings:
  aws:elasticbeanstalk:container:nodejs:
    NodeVersion: 8.15.0
    NodeCommand: npm run start:production
  aws:elb:listener:443:
    ListenerEnabled: true
    InstancePort: '80'
    SSLCertificateId: arn:aws:iam::912625699000:server-certificate/usage-svc-dev-eb-x509
    ListenerProtocol: HTTPS
    InstanceProtocol: HTTP
  aws:elasticbeanstalk:environment:
    EnvironmentType: LoadBalanced
    ServiceRole: aws-elasticbeanstalk-service-role
  aws:elasticbeanstalk:healthreporting:system:
    SystemType: enhanced
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
EnvironmentTier:
  Type: Standard
  Name: WebServer
AWSConfigurationTemplateVersion: 1.1.0.0
